baseURL = "https://armum.eu/"
languageCode = "pl-pl"
title = "Field Laboratory"
theme = "hugo-coder"

defaultContentLanguage = "pl"
enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 6

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "armum"
  description = "Notatki, fotografia i eksperymenty techniczne."
  keywords = "blog, fotografia, technologia, hugo"
  dateFormat = "2006-01-02"
  since = 2026
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
  customSCSS = ["scss/custom.scss"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 1
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[languages.pl]
  languageName = "PL"

  [[languages.pl.menu.main]]
    name = "Teksty"
    weight = 1
    url = "posts/"

  [[languages.pl.menu.main]]
    name = "Projekty"
    weight = 2
    url = "projects/"

  [[languages.pl.menu.main]]
    name = "Zdjęcia"
    weight = 3
    url = ""
    [languages.pl.menu.main.params]
      disabled = true

  [[languages.pl.menu.main]]
    name = "Tematy"
    weight = 4
    url = ""
    [languages.pl.menu.main.params]
      disabled = true

  [[languages.pl.menu.main]]
    name = "Szukaj"
    weight = 5
    url = ""
    [languages.pl.menu.main.params]
      disabled = true
